### ISSUE TITLE
Better Bot Spam Feuture

### ISSUE THREAD

**Issue by Justiniscoding** [RedYetiDev/blooket.js#6]
I have a way to create a better bot spam function that you can interact with every bot. try seeing if this works:
```js
var Blooket = require(‘blooket.js’);
var games = [];
function spam(pin,name,animal,bots){
    for(var i = 0; i < bots; i++){
        var game = new Blooket();
        game.join(pin,name,animal);
        games.push(game);
    }
    games.forEach(game => {
        game.on //whatever script they want 
    });
}
```
it puts every game in an array so you can do things with them individualy

**Comment by RedYetiDev** [comment]
I need to do some validation, and this would be network heavy, this might work, but I also have a few other theories. One is to do something like these steps for the script.
1. Script gets the WebSocket
2. Script sends (bot amount) requests with names.
3. Script logs each name to a botnames variables
4. Script runs a `for`loop for each name sending an answer.

PS: If you want to highlight your script, instead of using 
```
    ```
    const Blooket = require("blooket.js")
    ```
```
use
```no-highlight
    ```js
    const Blooket = require("blooket.js")
    ```
```
for this result
```js
const Blooket = require("blooket.js")
```

**Comment by RedYetiDev** [comment]
For the `BotSpam` function, I am not going to add your feature, but, I will test it, and if it works, I will add it to README as a fully functional BotSpam function.
My reason behind this, is that the bots each are going to have there own websocket, and that function is for more intense computers.

**Comment by Justiniscoding** [comment]
@RedYetiDev  what else will be new in v 1.2

**Comment by RedYetiDev** [comment]
Some new features in v1.2 are going to be 
- BotSpam takes almost no time to send bots (The time it takes is just to find and connect to the websocket)
- Tower Defense Mode Support
- Random Blook fix (From you)
- Added a `incorrect` event (When you get the question wrong it is emitted)
- And more
